name: postgres-env
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - psycopg2-binary
    - python-dotenv
    - sqlalchemy
    - flask
    - pandas
    - numpy
    - jupyter